# 记得修改admin的密码
admin:
  cookie_key: admin_token
  password: '123456'

# 成员 可以不填写完整数据 name必填
members:
  - atcoder: ConanYu
    codeforces: ConanYu
    grade: 2017
    name: ConanYu
    luogu: YuZining
    vjudge: ConanYu
    nowcoder: 6693394

# proxy 需要的可以填写 可以填写socks5的url
proxies:
  http: ~
  https: ~

# 以下为必填项
vjudge:
  password: ~
  username: ~
